wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.16.5
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712231726.0
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 19
      - 23
      - 37
      4: 3.10.10
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 64
drop:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 50
f1:
  desc: null
  value: 48
f2:
  desc: null
  value: 64
f3:
  desc: null
  value: 64
fc_layer_size:
  desc: null
  value: 1024
learning_rate:
  desc: null
  value: 0.01
architecture_name:
  desc: null
  value: TSR-CNN2
dataset_name:
  desc: null
  value: GTSRB
