wandb_version: 1

batch_size:
  value: 64
epochs:
  value: 50
f1:
  value: 48
f2:
  value: 32
f3:
  value: 32
f4:
  value: 48
f5:
  value: 24
fc_layer_size:
  value: 128
learning_rate:
  value: 0.0001
